for문

```{r}
for(i in 1:10){
  print(i)
}
```

```{r}
for(i in c(1,3,5)){
  print(i)
}
```

1\~100까지의 홀수만 출력하기

```{r}
for(i in (1:100)%%2!=0){
  print(i)
}
```

```{r}
for(i in 1:10){
  print(paste(i, "=>", sqrt(i)))
}
# ********************************************
for(i in 1:10){
  cat(paste(i, "=>", sqrt(i),"\n"))
}

```

1부터 100까지의 짝수의 합계 구하기

```{r}
data <- 1:100;data

paste(min(data), "와", max(data), "사이의 짝수 합계는", (sum(ifelse(data%%2==0, data, 0))),"입니다.")
```

```{r}
excel <- read.csv("./Data/excel.csv")
head(excel)
```

```{r}
data <- excel$q3
sumEven <- sumOdd <- 0

for(i in data){
  if(i %% 2 == 0){
    sumEven = sumEven + i
  }else{
    sumOdd = sumOdd + i
  }
}

cat("홀수의 합은", sumOdd, "이고 짝수의 합은", sumEven, "입니다.")
```

```{r}
for(i in 1:9){
  cat("2 X", i, "=", 2*i, "\n")
}
```

```{r}
gugu <- function(){
  for(i in 1:9){
  cat("2 X", i, "=", 2*i, "\n")
}
}
```

```{r}
gugu()
```

```{r}
gugu2 <- function(i){
  for(j in 1:9){
    if(i>2 && i<=9){
    cat(i, "X", j, "=", j*i, "\n")
    }else{
      NA
    }
  }
}

```

```{r}
gugu2(3)
```

```{r}
gugu3 <- function(i,j){
  for(j in 1:j){
    cat(i,"X",j,"=",i*j,"\n")
  }
}

gugu3(2,12)
```

iXj

i=j이하 짝수

```{r}
gugu4 <- function(i,j){
  for(seq(i,j,2)){
  cat(i,"X",j,"=",i*j,"\n")
}

gugu4(2,8)
```

```{r}
score <- c(85,95,89)
name <- c("유비", "관우", "장비")
cat(paste(name, ":", score, "\n"), sep="")
```

while

```{r}
i <- 0
while(i<10){
  i = i + 1
  print(i)
}
```

```{r}
i <- 0
while(T){
  i = i + 1
  print(i)
  if(i>9){
    break
  }
}
```

repeat

```{r}
i <- 0
repeat{
  i=i+1
  if(i>10){
    break
  }
  print(i)
}
```
