### 선굵기 변경하기

```{r}
x<-c(1,3,5,2,9,10)
plot(x,
     type="b",
     col=c(rep("red",5),"blue"),
     lwd=c(rep("1",5),"3") # line width
)
```

### 한 화면에 차트 여러개 그려서 비교하기

```{r}
# figure
price<- runif(10,1,100)
plot(price)
```

```{r}
par(mfrow=c(2,2))# 2행 2열
#par(mfrow=c(1,4))
#par(mfrow=c(4,1))
plot(price,type="l")
plot(price,type="o")
plot(price,type="h")
plot(price,type="s")
```

### pch 속성으로 그리기

```{r}
par(mfrow=c(2,2))
plot(price,type="o",pch=5)
plot(price,type="o",pch=15)
plot(price,type="o",pch=20,col="blue")
plot(price,type="o",pch=c(rep(20,8),15,15),
     col="orange",
     cex=c(rep(1,8),3,1)) # 1이 default
```

### 중첩 자료 시각화

```{r}
x<-c(1,2,3,4,2,4)
y<-rep(2,6)
plot(x,y)
```

### 중첩자료 확인

```{r}
table(x,y)
```

### Method #1

```{r}
xy.df<-as.data.frame(table(x,y))
xy.df
plot(x,y,
     pch=15,
     cex=2*xy.df$Freq) # Freq=1,2,1,2
```

### Method #2 중복데이터가 많을 경우 (sunflowerplot)

```{r}
x<-c(1,1,1,2,2,2,2,2,2,3,3,4,5,6)
y<-c(1,1,4,2,3,2,2,2,3,2,1,1,1,1)
as.data.frame(table(zz))
zz<-data.frame(x,y)
sunflowerplot(zz)
# 선의 개수 = 중복데이터 수
# ex. 십자 = 중복 4개
```

sunflowerplot으로 iris의 sepal.length와 sepal.width의 산포도 그리기

```{r}
sepal_length<-iris$Sepal.Length
sepal_width<-iris$Sepal.Width
lw<-data.frame(sepal_length,sepal_width)
sunflowerplot(lw)
```

chart 2개를 겹쳐서 출력하기 (dotchart)

```{r}
x<-1:10

# 그라데이션 열개 지정
mycol<-rgb(0,0,1,seq(0,1,0.1))

dotchart(x,
         col="red")
# par이 중간에 들어감 주의
par(new=T)
barplot(x,
        col=mycol # == 투명도 주기 위함
        )
```

# 상자 수염 그래프

: 이상치 확인 (정규분포에서 과도하게 벗어난 데이터가 있는지 여부 확인)

```{r}
abc<-c(110,300,150,280,310)
boxplot(abc)
# summary 결과를 표시
# 최솟값, 1/4분위, 중앙값, 평균, 3/4분위, 최댓값
```

```{r}
summary(abc)

```

```{r}
abc<-c(110,300,150,280,310)
boxplot(abc,
        col="yellow",
        horizontal=T)
# 최솟값, 1/4분위, 중앙값, 평균, 3/4분위, 최댓값
```

```{r}
def<-c(1,1,1,1,1,2,5)
summary(def)
```

```{r}
boxplot(def)
# 이상치 (5)를 제외한 나머지 데이터 사용함
# ex. 수영에서 최대치 최소치를 제외한 나머지 값으로 평균 내는 등
```

자동차의 제동거리

```{r}
head(cars) # speed, distance (제동거리)
str(cars)
```

```{r}
plot(cars$speed,cars$dist)
```

```{r}
hist(cars$dist)
```

```{r}
boxplot(cars$dist)
```

# 차트 디자인

```{r}
# par(family="AppleGothic")

x<-c(1, 3, 6, 8, 9)
y<-c(12,56,78,32,9)
plot(x,y)

# (3,3)과 (4,4)를 연결하는 선분 그리기
segments(6,78, 8,32, col="red")

# 화살표 그리기
arrows(3,56,1,12,col="blue")
arrows(5,10,7,70)

# 글자쓰기
text(4,40,"This is a 샘플",srt=50) # srt=각도

# 테두리 활용하기
mtext("Character", side=4, adj=0) # side: x축부터 시계방향 (1~4), adj: 위치 (0~1)

# 테두리 그리기
box(lty=1, col="red") # 생성된 plot상에 overlap

# 사각형 그리기
rect(4,20,6,30, density=10, col="red")

# x축 추가, y축의 40위치에 0~10까지 표시하고 색은 빨간색

axis(1,pos=40,at=0:10,col="red")

# y축 추가, x축의 6위치에 20~60까지 표시하고 색은 파란색
axis(2, pos=6,at=20:60,col="blue")
```

## 투표수가 높은 시군구의 후보별 득표수의 막대그래프에 시군구별 투표수 표시하기

```{r}
election<-read.csv("./Data/election_2022.csv")
election
library(dplyr)
vote_top5<-arrange(election,desc(투표수))[1:5,]
vote_top5

district<-paste(vote_top5$광역시도,vote_top5$시군구)
district<-as.data.frame(district)
district[,2:4]<-cbind(vote_top5$이재명,vote_top5$윤석열,vote_top5$심상정)
colnames(district)<-c("시군구","이재명","윤석열","심상정")

district_matrix<-t(district)

district_matrix
district
vote_count<-apply(district[1:5,2:4],1,sum)
vote_count
barplot(district_matrix[2:4,],
        main="투표수가 높은 시군구의 후보별 득표수",
        names.arg = district_matrix[1,],
        cex.names = 0.7,
        ylim=c(0,600000),
        col=c("skyblue","red","yellow"))
text(1,40,vote_count[1])
```

```{r}
colnames(district_matrix)<-district_matrix[1,]
district_matrix<-district_matrix[-1,]
rownames(district_matrix)

line<-0.7

barplot(district_matrix[2:4,],
        main="투표수가 높은 시군구의 후보별 득표수",
        names.arg = district_matrix[1,],
        cex.names = 0.7,
        ylim=c(0,600000),
        col=c("skyblue","red","yellow"),
        legent.text=T)
for(i in 1:5){
text(line,vote_count[i]+20000,vote_count[i],cex=0.8)
  line=line+1.2
}
```

```{r}
line<-0.7
barplot(district_matrix,
        main="투표수가 높은 시군구의 후보별 득표수",
        names.arg = district_matrix[1,],
        cex.names = 0.7,
        ylim=c(0,600000),
        col=c("skyblue","red","yellow"),
        legend.text=T)
for(i in 1:5){
text(line,vote_count[i]+20000,vote_count[i],cex=0.8)
  line=line+1.2
}
```

```{r}
vote_count
district
total<-apply(district[1:5,2:4],1,sum)
for(i in 1:5){
  total_rate[i,1:3]<-district[i,2:4]/total[i]
}
```

```{r}
rownames(total_rate)<-district[1:5,1]
total_rate<-t(total_rate)
total_rate
```

```{r}
options(scipen=100)
line<-0.7
barplot(district_matrix,
        main="투표수가 높은 시군구의 후보별 득표수",
        names.arg = colnames(district_matrix),
        cex.names = 0.7,
        ylim=c(0,600000),
        col=c("skyblue","red","green"),
        legend.text=T)
for(i in 1:5){
  for(j in 1:3){
  text(line,(sum(as.numeric(district_matrix[1:j,i]))-(as.numeric(district_matrix[j,i])/2)),paste(round(total_rate[j,i]*100,1.5),"%"),cex=0.7)
  }
  line=line+1.2
}

```

```{r}
total_rate
```

## qplot()을 이용한 산점도

```{r}
library(ggplot2)
```

```{r}
qplot(Sepal.Length, Petal.Length, 
      data=iris, 
      col=Species,
      size=Petal.Width) # 3차원으로 표현할때
```

## 수학 함수의 시각화

y=x\^2

```{r}
f<-function(x){
  y=x^2
  return(y)
}
```

```{r}
x<-1:3
f(x)
```

```{r}
x<-seq(-5,5,0.1)
plot(x, f(x),
     type = "l")
```

y=x\^2+2x+3

```{r}
fu<-function(x){
  y=x^2+2*x+3
  return(y)
}
```

```{r}
x<-seq(-6,4,0.1)
plot(x, fu(x),
     type = "l")
```
