# 회귀분석

단순회귀분석과 다중회귀분석

```{r}
regression<-read.csv("./Data/regression.csv")
head(regression)
tail(regression)
```

```{r}
str(regression)
```

```{r}
summary(regression$Height)
summary(regression$Weight)
```

```{r}
plot(regression$Height,
     regression$Weight)
```

```{r}
cor(regression$Height,regression$Weight)
# 0.9672103
```

```{r}
# 회귀선 (중심선, 평균선)
plot(regression$Weight~regression$Height)
# 회귀식 : lm(종속변수~독립변수)
r<-lm(regression$Weight~regression$Height)
abline(r, col="red")
```

분석결과

```{r}
summary(r)
```

p-value: \< 0.00000000000000022 (\< 0.05)

Adjusted R-squared: 0.9333 \<- 예측력

Residual standard error: 6.355 \<- 표준오차

intercept: 절편b

```{r}
r
```

y=ax+b

몸무게=0.6147\*키+(-40.8659)

키가 170cm인 사람의 몸무게를 예측

```{r}
(0.6147*170-40.8659)+6.355
(0.6147*170-40.8659)-6.355

# 표준오차를 적용한 키가 170인 사람의 몸무게
paste((0.6147*170-40.8659)-6.355,"~",(0.6147*170-40.8659)+6.355)
```

# IQ

```{r}
iq<-read.csv("./Data/IQ.csv")
str(iq)
```

### (1)IQ가 126인 사람의 성적을 예측해보세요

```{r}
iqR<-lm(iq$성적~iq$IQ)
```

```{r}
cor(iq$성적,iq$IQ)
summary(iq$성적)
summary(iq$IQ)

boxplot(iq$성적,iq$IQ)
```

```{r}
plot(iq$성적~iq$IQ)
abline(iqR,col="red")
```

```{r}
iqR
```

```{r}
summary(iqR)
paste((0.6714*126)-3.322,"~",(0.6714*126)+3.322)
```

(2) 성적과 가장 관련이 깊은 항목은?

```{r}
iq
iqRelation<-lm(iq$성적~iq$IQ+iq$TV시청.시간+iq$다니는.학원수+iq$게임하는.시간)
summary(iqRelation)

a<-iq[,-1]
max(abs(cor(a)))
abs(cor(a))
```

(3) 학원을 몇 군데 다녀야 90점이 될까?

```{r}
score_tutor<-lm(iq$다니는.학원수~iq$성적)
```

```{r}
plot(iq$다니는.학원수~iq$성적)
abline(score_tutor,
       col="red")
```

```{r}
summary(score_tutor)

paste(0.1241*90-7.8916-0.7882,"~",0.1241*90-7.8916+0.7882)
```

### 다중회귀분석

여러개의 항목들로 구성된 식으로 예측하는 방법

```{r}
data("attitude")
help(attitude)
attitude
```

```{r}
str(attitude)
```

```{r}
plot(attitude)
```

rating을 제외한 변수들이 rating에 어떤 영향을 미치는지

```{r}
model<-lm(rating~., data=attitude)
model
```

```{r}
summary(model)
cor(attitude)
```

## 예측력을 향상

```{r}
reduced<-step(model,direction="backward") # backward: 제일 필요없는 것부터 제거
```

```{r}
summary(reduced)
# step 결과는 다시 step 불가
```

```{r}
reduced
```

### iris에 대한 다중 회귀분석

```{r}
head(iris)
irisRe<-lm(as.numeric(Species)~.,data=iris)
summary(irisRe)
irisRe
```

```{r}
irisModel<-step(irisRe,direction="backward")
summary(irisModel)

```

```{r}
summary(irisModel)
findSpecies<-function(Sepal.Length,Petal.Length,Petal.Width){
  z<-(-0.13624*Sepal.Length+0.25213*Petal.Length+0.58689*Petal.Width)+1.1447
  return(z)
}
tail(iris)
```

```{r}
samp <- c(sample(1:50,35),sample(51:100,35),sample(101:150,35))


sl.sample <- iris[samp[1],]
pl.sample <- iris[samp[2],]
pw.sample <- iris[samp[3],]
round(findSpecies(iris$Sepal.Length,iris$Petal.Length,iris$Petal.Width),0)
```
