# 인공신경망을 이용한 평균 예측율 구하기

```{r}
library(nnet)
library(caret)
```

```{r}
nnetFun<-function(n){
  for(i in 1:n){
    if(i==1){
      resultVec=c()
    }
    samp<-createDataPartition(iris$Species,p=0.7,list=F)
    data.train<-iris[samp,]
    data.test<-iris[-samp,]
    x<-subset(data.test,select=-Species)
    y<-data.test$Species
    model.nnet<-nnet(Species~.,data=data.train,size=3)
    pred.nnet<-predict(model.nnet,x,type="class")
    resultVec=append(resultVec,mean(pred.nnet==y))
  }
  cat("------------------------------\n")
  cat("예측율\n",resultVec,"\n")
  cat("------------------------------\n")
  cat("평균예측율\n",mean(resultVec),"\n")
}
```

```{r}
# 함수 nnetFun 생성 (n회 시행)
nnetFun(5)
```

randomForest의 평균예측율 함수 구하기

```{r}
library(randomForest)
```

```{r}
rfFun<-function(n){
  for(i in 1:n){
    if(i==1){
      resultVec=c()
    }
    samp<-createDataPartition(iris$Species,p=0.7,list=F)
    data.train<-iris[samp,]
    data.test<-iris[-samp,]
    x<-subset(data.test,select=-Species)
    y<-data.test$Species
    rf<-randomForest(Species~.,data=data.train,ntree=3)
    pred<-predict(rf,x)
    resultVec=append(resultVec,mean(pred==y))
    
  }
  cat("------------------------------\n")
  cat("예측율\n",resultVec,"\n")
  cat("------------------------------\n")
  cat("평균예측율\n",mean(resultVec),"\n")
}
```

```{r}
rfFun(5)
```

svm의 평균예측율 함수 구하기

```{r}
library(e1071)
```

```{r}
svmFun<-function(n){
  for(i in 1:n){
    if(i==1){
      resultVec=c()
    }
    samp<-createDataPartition(iris$Species,p=0.7,list=F)
    data.train<-iris[samp,]
    data.test<-iris[-samp,]
    x<-subset(data.test,select=-Species)
    y<-data.test$Species
    model<-svm(Species~.,data=data.train)
    pred<-predict(model,x)
    resultVec=append(resultVec,mean(pred==y))
  }
  cat("------------------------------\n")
  cat("예측율\n",resultVec,"\n")
  cat("------------------------------\n")
  cat("평균예측율\n",mean(resultVec),"\n")
}
```

```{r}
svmFun(5)
```
